In [ ]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
path = "/content/drive/MyDrive/testes/Crime_Data_from_2020_to_Present.csv"

data = pd.read_csv(path)

In [ ]:

data['year'] = data['DATE OCC'].str.split(' ').str[0].str.split('/').str[2]
data['month'] = data['DATE OCC'].str.split(' ').str[0].str.split('/').str[1]
data['day'] = data['DATE OCC'].str.split(' ').str[0].str.split('/').str[0]

In [ ]:
data

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON,year,month,day
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,998.0,NaN,NaN,1900 S LONGWOOD AV,NaN,34.0375,-118.3506,2020,01,03
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628,2020,08,02
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002,2020,04,11
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,NaN,NaN,NaN,14000 RIVERSIDE DR,NaN,34.1576,-118.4387,2020,10,03
4,220614831,08/18/2022 12:00:00 AM,08/17/2020 12:00:00 AM,1200,6,Hollywood,666,2,354,THEFT OF IDENTITY,...,NaN,NaN,NaN,1900 TRANSIENT,NaN,34.0944,-118.3277,2020,17,08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986495,242011172,08/20/2024 12:00:00 AM,08/17/2024 12:00:00 AM,2300,20,Olympic,2033,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,NaN,NaN,NaN,3700 WILSHIRE BL,NaN,34.0617,-118.3066,2024,17,08
986496,240710284,07/24/2024 12:00:00 AM,07/23/2024 12:00:00 AM,1400,7,Wilshire,788,1,510,VEHICLE - STOLEN,...,NaN,NaN,NaN,4000 W 23RD ST,NaN,34.0362,-118.3284,2024,23,07
986497,240104953,01/15/2024 12:00:00 AM,01/15/2024 12:00:00 AM,100,1,Central,101,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,NaN,NaN,NaN,1300 W SUNSET BL,NaN,34.0685,-118.2460,2024,15,01
986498,240309674,04/24/2024 12:00:00 AM,04/24/2024 12:00:00 AM,1500,3,Southwest,358,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,NaN,NaN,NaN,FLOWER ST,JEFFERSON BL,34.0215,-118.2868,2024,24,04
986499,240910892,08/13/2024 12:00:00 AM,08/12/2024 12:00:00 AM,2300,9,Van Nuys,914,1,510,VEHICLE - STOLEN,...,NaN,NaN,NaN,6900 VESPER AV,NaN,34.1961,-118.4510,2024,12,08

In [ ]:
data['AREA'].unique()

array([ 7,  1,  3,  9,  6, 18, 13, 19,  2, 10,  8, 20,  4, 21, 11, 12, 14,
       15,  5, 16, 17])

In [ ]:
data_process = data.groupby(['AREA', 'month', "year"])['AREA'].count().reset_index(name='counts')

data_process.sort_values(by=['AREA', 'year', 'month'])

      AREA month  year  counts
0        1    01  2020     453
5        1    02  2020     369
10       1    03  2020     366
15       1    04  2020     389
20       1    05  2020     372
...    ...   ...   ...     ...
3234    21    27  2024     168
3239    21    28  2024     132
3244    21    29  2024     133
3249    21    30  2024     130
3254    21    31  2024      82

[3255 rows x 4 columns]